apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: ilf20vljm-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ilf20vljm-python 
  name: ilf20vljm-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: ilf20vljm-python
    weight: 100 
